package complexbody.io.sensors.datatypes.enums;

public enum eSensorExtType {
	UNDEFINED,
	ACCELERATION,
	ACOUSTIC,
	BUMP,
	EATABLE_AREA,
	MANIPULATE_AREA,
	OLFACTORIC,
	TACTILE,
	VISION,
	VISION_SELF,
	VISION_NEAR,
	VISION_MEDIUM,
	VISION_FAR,
	ACOUSTIC_SELF,
	ACOUSTIC_NEAR,
	ACOUSTIC_MEDIUM,
	ACOUSTIC_FAR,
	POSITIONCHANGE,
	RADIATION,
	VISION_CARRIED_ITEMS
}
