/**
 * @author deutsch
 * 07.05.2009, 09:54:33
 * 
 * $Rev::                      $: Revision of last commit
 * $Author::                   $: Author of last commit
 * $Date::                     $: Date of last commit
 */
package bw.utils.enums;

/**
 * TODO (deutsch) - insert description 
 * 
 * @author deutsch
 * 07.05.2009, 09:54:33
 * 
 */
public enum eConfigEntries {
	// single entries
	CONTENT,
	MAXCONTENT,
	INCREASERATE,
	DECAYRATE,
	CHANGE,
	LOWERBOUND,
	UPPERBOUND,
	ALIVE,
	SELFHEALINGRATE,
	ISDEADTHRESHOLD,
	FRACTION,
	SELFREGULATIONADAPTION,
	GARBAGENUTRITIONTYPE,
	PAINTHRESHOLD,
	HEALTHPENALTY,
	HURTTHRESHOLD,
	ENERGYCONSUMPTION,
	ANGLE,
	RANGE,
	OFFSET,
	WEIGHT,
	RADIUS,
	COLOR, 
	SPEED,
	
	//
	ACTIVATE,
	
	// lists
	NUTRITIONCONFIG,
	EXTSENSORCONFIG,
	EXTACTUATORCONFIG,
	INTSENSORCONFIG,
	INTACTUATORCONFIG,
	NUTRITIONS,
	EXTSENSORS,
	EXTACTUATORS,
	INTSENSORS,
	INTACTUATORS,
	
	//BODYPARTS
	BODY,	
	//internal systems
	INTSYS,
	INTSYS_FAST_MESSENGER_SYSTEM,
	INTSYS_FLESH,
	INTSYS_HEALTH_SYSTEM,
	INTSYS_INTERNAL_ENERGY_CONSUMPTION,
	INTSYS_INTERNAL_SYSTEM,
	INTSYS_SLOW_MESSENGER_SYSTEM,
	INTSYS_STAMINA_SYSTEM,
	INTSYS_STOMACH_SYSTEM,
	INTSYS_TEMPERATURE_SYSTEM,
	
	//intrabodysysems
	INTRA,
	INTRA_DAMAGE_NUTRITION,
	INTRA_DAMAGE_TEMPERATURE,
	INTRA_BODYCOLOR,
	INTRA_GROWTH,
	
	//interbodyworldsystems
	INTER,
	INTER_DAMAGE_BUMP,
	INTER_DAMAGE_LIGHTNING,
	INTER_CONSUME_FOOD,
	
	EXTERNAL_IO,
	INTERNAL_IO,
	
	//sensors
	SENSOR_EXT,
	SENSOR_INT,
	SENSOR_EXT_ACOUSTIC, 
	SENSOR_EXT_VISION,
	SENSOR_EXT_OLFACTORIC,
	SENSOR_EXT_TACTITLE,
	SENSOR_EXT_TACTILE_BUMP,
	SENSOR_EXT_ACCELERATION,
	SENSOR_EXT_VISION_EATABLE_AREA,
	
	
	//actuators
	ACTUATOR_EXT,
	ACTUATOR_INT,
	ACTUATOR_EXT_EAT,
	ACTUATOR_EXT_MOVE,
	
	//limbs
	TENTACLE,
	TENTACLE_LEFT,

	//brain
	BRAIN,	
	
	//SENSORSEXTTYPE
	UNDEFINED,
	ACCELERATION,
	ACOUSTIC,
	BUMP,
	EATABLE_AREA,
	OLFACTORIC,
	TACTILE,
	VISION,
	
	//SENSORSINTTYPE
	ENERGY_CONSUMPTION,
	HEALTH_SYSTEM,
	STAMINA,
	STOMACH,
	
	//NUTRITIONS
	PROTEIN,
	FAT,
	VITAMIN,
	CARBOHYDRATE,
	WATER,
	MINERAL,
	TRACEELEMENT,
	VITAMIN_A,
	VITAMIN_B,
	VITAMIN_C,
	UNDIGESTABLE,
}

