{
 "title": "SiMA",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Sexual Drive Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "F39_SeekingSystem_LibidoSource",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ORIFICE_ORAL_AGGRESSIV_MUCOSA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F39" }
     ]
    },
    {
     "measurement": "ORIFICE_ORAL_LIBIDINOUS_MUCOSA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F39" }
     ]
    },
    {
     "measurement": "STOMACH",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F39" }
     ]
    }
   ]
  },
  {
   "title": "F40_NeurosymbolizationOfLibido",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Libido",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F40" }
     ]
    }
   ]
  },
  { "title": "Self-presentation Drive Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "F01_SensorsMetabolism",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ENERGY_CONSUMPTION",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    },
    {
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    },
    {
     "measurement": "STAMINA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    },
    {
     "measurement": "STOMACH_ENERGY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    },
    {
     "measurement": "STOMACH_INTESTINE_TENSION",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    },
    {
     "measurement": "STOMACH_TENSION",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F01" }
     ]
    }
   ]
  },
  {
   "title": "F02_NeurosymbolizationOfNeeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ADREANLIN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    },
    {
     "measurement": "BLOODSUGAR",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    },
    {
     "measurement": "RECTUM",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    },
    {
     "measurement": "STAMINA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    },
    {
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    },
    {
     "measurement": "STOMACH",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F02" }
     ]
    }
   ]
  },
  { "title": "Body Perception Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "F12_SensorsBody",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "CRYING_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F12" }
     ]
    },
    {
     "measurement": "HEART_BEAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F12" }
     ]
    },
    {
     "measurement": "MUSCLE_TENSION_ARMS_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F12" }
     ]
    },
    {
     "measurement": "MUSCLE_TENSION_Legs_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F12" }
     ]
    },
    {
     "measurement": "SWEAT_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F12" }
     ]
    }
   ]
  },
  { "title": "Drive Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "F64_PartialSexualDrives",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ORIFICE_ORAL_AGGRESSIV_MUCOSA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F64" }
     ]
    },
    {
     "measurement": "ORIFICE_ORAL_LIBIDINOUS_MUCOSA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F64" }
     ]
    },
    {
     "measurement": "STOMACH",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F64" }
     ]
    }
   ]
  },
  {
   "title": "F48_AccumulationOfQuotaOfAffectsForDrives",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Pleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F48" }
     ]
    }
   ]
  },
  { "title": "Perception Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "F14_ExternalPerception",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "CRYING_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F14" }
     ]
    },
    {
     "measurement": "HEART_BEAT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F14" }
     ]
    },
    {
     "measurement": "MUSCLE_TENSION_ARMS_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F14" }
     ]
    },
    {
     "measurement": "MUSCLE_TENSION_Legs_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F14" }
     ]
    },
    {
     "measurement": "SWEAT_INTENSITY",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F14" }
     ]
    }
   ]
  },
  {
   "title": "F45_DischargeOfPsychicIntensity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ANAL_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "ANAL_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "GENITAL_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "GENITAL_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "ORAL_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "ORAL_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "PHALLIC_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "PHALLIC_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "RECTUM_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "RECTUM_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "STAMINA_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "STAMINA_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "STOMACH_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    },
    {
     "measurement": "STOMACH_Lib",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F45" }
     ]
    }
   ]
  },
  { "title": "Defense Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "F63_CompositionOfEmotions - Drives",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "rDriveAggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "rDriveLibid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "rDrivePleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "rDriveUnpleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    }
   ]
  },
  {
   "title": "F63_CompositionOfEmotions - Emotions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ANGER_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANGER_Libid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANGER_Pleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANGER_Unpleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANXIETY_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANXIETY_Libid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANXIETY_Pleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "ANXIETY_Unpleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "JOY_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "JOY_Libid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "JOY_Pleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "JOY_Unpleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "MOURNING_Aggr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "MOURNING_Libid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "MOURNING_Pleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    },
    {
     "measurement": "MOURNING_Unpleasure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F63" }
     ]
    }
   ]
  },
  { "title": "Actuator Track", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "F31_NeuroDeSymbolizationActionCommands",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "FORWARD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F31" }
     ]
    },
    {
     "measurement": "BACKWARD",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F31" }
     ]
    },
    {
     "measurement": "TURN_LEFT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F31" }
     ]
    },
    {
     "measurement": "TURN_RIGHT",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=", "value": "F31" }
     ]
    }
   ]
  }
 ]
}