/**
 * E41_Libidostasis.java: DecisionUnits - pa.modules._v30
 * 
 * @author deutsch
 * 03.03.2011, 15:18:57
 */
package pa.modules._v30;

import java.util.ArrayList;
import java.util.HashMap;

import pa.interfaces._v30.eInterfaces;
import pa.interfaces.receive._v30.I1_10_receive;
import pa.interfaces.receive._v30.I1_9_receive;
import pa.interfaces.send._v30.D1_1_send;
import pa.interfaces.send._v30.I1_10_send;
import pa.storage.clsLibidoBuffer;

import config.clsBWProperties;

/**
 * DOCUMENT (deutsch) - insert description 
 * 
 * @author deutsch
 * 03.03.2011, 15:18:57
 * 
 */
public class E41_Libidostasis extends clsModuleBase implements I1_9_receive, I1_10_send, D1_1_send {
	public static final String P_MODULENUMBER = "41";
	
	private clsLibidoBuffer moLibidoBuffer;
	private double mrTempLibido;
	
	/**
	 * DOCUMENT (deutsch) - insert description 
	 * 
	 * @author deutsch
	 * 03.03.2011, 15:47:47
	 *
	 * @param poPrefix
	 * @param poProp
	 * @param poModuleList
	 * @throws Exception 
	 */
	public E41_Libidostasis(String poPrefix, clsBWProperties poProp,
			HashMap<Integer, clsModuleBase> poModuleList, HashMap<eInterfaces, ArrayList<Object>> poInterfaceData, clsLibidoBuffer poLibidoBuffer) throws Exception {
		super(poPrefix, poProp, poModuleList, poInterfaceData);
		
		moLibidoBuffer = poLibidoBuffer;
		mrTempLibido = 0;
		
		applyProperties(poPrefix, poProp);	
	}
	
	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 14.04.2011, 17:36:19
	 * 
	 * @see pa.modules._v30.clsModuleBase#stateToHTML()
	 */
	@Override
	public String stateToHTML() {
		String html ="";
		
		html += valueToHTML("moLibidoBuffer", moLibidoBuffer);
		html += valueToHTML("mrTempLibido", mrTempLibido);		
		
		return html;
	}		
	
	public static clsBWProperties getDefaultProperties(String poPrefix) {
		String pre = clsBWProperties.addDot(poPrefix);
		
		clsBWProperties oProp = new clsBWProperties();
		oProp.setProperty(pre+P_PROCESS_IMPLEMENTATION_STAGE, eImplementationStage.BASIC.toString());
				
		return oProp;
	}
	
	private void applyProperties(String poPrefix, clsBWProperties poProp) {
		//String pre = clsBWProperties.addDot(poPrefix);
	
		//nothing to do
	}	
	
	@Override
	protected void setProcessType() {mnProcessType = eProcessType.PRIMARY;}
	@Override
	protected void setPsychicInstances() {mnPsychicInstances = ePsychicInstances.ID;}
	@Override
	protected void setModuleNumber() {mnModuleNumber = Integer.parseInt(P_MODULENUMBER);}

	private void updateTempLibido() {
		mrTempLibido = moLibidoBuffer.send_D1_2();
	}
	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:19:22
	 * 
	 * @see pa.modules._v30.clsModuleBase#process_basic()
	 */
	@Override
	protected void process_basic() {
		 updateTempLibido();
		 mrTempLibido += 0.01; 
	}

	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:19:22
	 * 
	 * @see pa.modules._v30.clsModuleBase#process_draft()
	 */
	@Override
	protected void process_draft() {
		 updateTempLibido();
		// TODO (deutsch) - Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:19:22
	 * 
	 * @see pa.modules._v30.clsModuleBase#process_final()
	 */
	@Override
	protected void process_final() {
		 updateTempLibido();
		// TODO (deutsch) - Auto-generated method stub
		
	}

	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:19:22
	 * 
	 * @see pa.modules._v30.clsModuleBase#send()
	 */
	@Override
	protected void send() {
		send_I1_10(new HashMap<String, Double>());
		send_D1_1(mrTempLibido);
	}

	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:49:01
	 * 
	 * @see pa.interfaces.send._v30.I1_10_send#receive_I1_10(java.util.HashMap)
	 */
	@Override
	public void send_I1_10(HashMap<String, Double> poHomeostasisSymbols) {
		((I1_10_receive)moModuleList.get(43)).receive_I1_10(poHomeostasisSymbols);
		putInterfaceData(I1_10_send.class, poHomeostasisSymbols);
		
	}

	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 03.03.2011, 15:49:01
	 * 
	 * @see pa.interfaces.receive._v30.I1_9_receive#receive_I1_9(java.util.HashMap)
	 */
	@Override
	public void receive_I1_9(HashMap<String, Double> poHomeostasisSymbols) {
		// TODO (deutsch) - Auto-generated method stub
		
	}
	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 09.03.2011, 17:25:10
	 * 
	 * @see pa.interfaces.send._v30.D1_1_send#send_D1_1(double)
	 */
	@Override
	public void send_D1_1(double prValue) {
		moLibidoBuffer.receive_D1_1(prValue);
		putInterfaceData(D1_1_send.class, prValue);
	}
	/* (non-Javadoc)
	 *
	 * @author deutsch
	 * 15.04.2011, 13:52:57
	 * 
	 * @see pa.modules._v30.clsModuleBase#setDescription()
	 */
	@Override
	public void setDescription() {
		moDescription = "The constant flow of libido/psychic energy provided by the neurosymbols originating from {E40} has to be buffered until the tension generated by the seeking system can be released. Module {E41} adds the incoming libido to a libido buffer. The total amount of buffered libido is forwarded as total amount of tension. Further, the sexual drives are split into aggressive and libidinous components.";
	}	
}
